name: Update Notebooks
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 12 * * *"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: make deps

      - name: Run Notebooks
        env:
          VULNCHECK_API_TOKEN: ${{ secrets.VULNCHECK_API_TOKEN }}
        run: make build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
